const ORDER_REQUEST = "ORDER_REQUEST"
const ORDER_SUCCESS = "ORDER_SUCCESS"
const ORDER_FAILURE = "ORDER_FAILURE"

export const order = {
  ORDER_REQUEST,
  ORDER_SUCCESS,
  ORDER_FAILURE,
}

export const SET_MAP_API = "SET_MAP_API"
